# Generated by Django 3.1.4 on 2021-01-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ns', 'not started'), ('og', 'on going'), ('cm', 'completed'), ('lt', 'late')], default='ns', max_length=2),
        ),
    ]
